services:
  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    container_name: ocelot-gateway
    build:
      context: .
      dockerfile: OcelotApiGateway/Dockerfile
    ports:
    - "5000:5000"
  productservice:
    image: ${DOCKER_REGISTRY-}productservice
    container_name: product-service
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
        - "5240:8081"
    depends_on:
      - rabbitmq


  inventoryservice:
    image: ${DOCKER_REGISTRY-}inventoryservice
    container_name: inventory-service
    build:
      context: .
      dockerfile: InventoryService/Dockerfile
    ports:
        - "5066:8081"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_LOGS: =-

